//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public string Descripcion { get; set; }
        public int Id_Empleado { get; set; }
        public int Id { get; set; }
    }
}
